--Bước 1: Tạo 4 login: 'LoginQTV','LoginNHANVIEN','LoginNHASI','LoginBENHNHAN'
USE [QLPKNK]
IF NOT EXISTS 
    (SELECT name
FROM QLPKNK.sys.server_principals
WHERE name in ('LoginQTV','LoginNHANVIEN','LoginNHASI','LoginBENHNHAN'))
BEGIN
    --Tạo 4 login: 'LoginQTV','LoginNHANVIEN','LoginNHASI','LoginBENHNHAN'
    CREATE LOGIN [LoginQTV] WITH PASSWORD = '12345678'
	,DEFAULT_DATABASE=[QLPKNK], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    CREATE LOGIN [LoginNHANVIEN] WITH PASSWORD = '12345678'
	,DEFAULT_DATABASE=[QLPKNK], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    CREATE LOGIN [LoginNHASI] WITH PASSWORD = '12345678'
	,DEFAULT_DATABASE=[QLPKNK], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    CREATE LOGIN [LoginBENHNHAN] WITH PASSWORD = '12345678'
	,DEFAULT_DATABASE=[QLPKNK], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
END
GO
USE [QLPKNK]
GO
--Tạo user cho 4 login trên csdl QLPKNK:
IF NOT EXISTS (SELECT [name]
FROM [sys].[database_principals]
WHERE [name] in ('userQTV','userNHANVIEN','userNHASI','userBENHNHAN'))
Begin
    CREATE USER [userQTV] 
    FOR LOGIN [LoginQTV] WITH DEFAULT_SCHEMA=[dbo];
    CREATE USER [userNHANVIEN] 
    FOR LOGIN [LoginNHANVIEN] WITH DEFAULT_SCHEMA=[dbo];
    CREATE USER [userNHASI] 
    FOR LOGIN [LoginNHASI] WITH DEFAULT_SCHEMA=[dbo];
    CREATE USER [userBENHNHAN] 
    FOR LOGIN [LoginBENHNHAN] WITH DEFAULT_SCHEMA=[dbo];
end
GO
-- PHÂN QUYỀN: Quan Tri Vien
IF NOT EXISTS (SELECT *
FROM sys.database_principals
WHERE name = 'QTV' AND type = 'R')
BEGIN
    CREATE ROLE [QTV];
    ALTER ROLE [QTV] ADD MEMBER [userQTV];

    GRANT ALTER ANY SCHEMA TO [userQTV];
    GRANT EXECUTE TO [userQTV];
    GRANT CONTROL TO [userQTV];
    GRANT SELECT, UPDATE, DELETE, INSERT TO [userQTV];
    GRANT CONTROL ON DATABASE::QLPKNK TO [userQTV];
END
ELSE
BEGIN
    ALTER ROLE [QTV] ADD MEMBER [userQTV];
END

-- PHÂN QUYỀN: NHASI
IF NOT EXISTS (SELECT *
FROM sys.database_principals
WHERE name = 'NHASI' AND type = 'R')
BEGIN
    CREATE ROLE [NHASI];
    ALTER ROLE [NHASI] ADD MEMBER [userNHASI];

    GRANT SELECT TO [NHASI];
    GRANT INSERT TO [NHASI];
END
ELSE
BEGIN
    ALTER ROLE [NHASI] ADD MEMBER [userNHASI];
END

-- PHÂN QUYỀN: NHANVIEN
IF NOT EXISTS (SELECT *
FROM sys.database_principals
WHERE name = 'NHANVIEN' AND type = 'R')
BEGIN
    CREATE ROLE [NHANVIEN];
    ALTER ROLE [NHANVIEN] ADD MEMBER [userNHANVIEN];

    GRANT SELECT TO [NHANVIEN];
    GRANT INSERT TO [NHANVIEN];
END
ELSE
BEGIN
    ALTER ROLE [NHANVIEN] ADD MEMBER [userNHANVIEN];
END

-- PHÂN QUYỀN: BENHNHAN
IF NOT EXISTS (SELECT *
FROM sys.database_principals
WHERE name = 'BENHNHAN' AND type = 'R')
BEGIN
    CREATE ROLE [BENHNHAN];
    ALTER ROLE [BENHNHAN] ADD MEMBER [userBENHNHAN];

    GRANT SELECT TO [BENHNHAN];
    GRANT INSERT TO [BENHNHAN];
END
ELSE
BEGIN
    ALTER ROLE [BENHNHAN] ADD MEMBER [userBENHNHAN];
END
-- -- To retrieve all Users
-- SELECT *
-- FROM QLPKNK.sys.database_principals
-- WHERE name LIKE 'u%';

-- SELECT *
-- FROM QLPKNK.sys.sql_logins
-- WHERE name LIKE 'Login%';